### ISSUE TITLE
Access schemeRepoURL locally

### ISSUE THREAD

**Issue by sb10** [wtsi-team112/ncov2019-artic-nf#11]
To avoid any process needing an internet connection, and to minimise needless git clones, if https://github.com/artic-network/artic-ncov2019.git has been manually cloned locally, it should be possible to use that local clone path directly.

**Comment by roamato** [comment]
Need to check consistency though. The repo contains the primers info and that might get updated e.g. when new versions are released

**Comment by sb10** [comment]
Is the current situation that you don't know what revision of artic-ncov2019.git was used in your analysis? I think knowing your revision (from on your own clone) for a whole run or multiple runs would be useful?

**Comment by roamato** [comment]
It gets recorded as part of the Nextflow execution. I like the suggesiton of making it explicit

**Comment by sb10** [comment]
For a heavily productionized environment, it may be preferable to bypass the `articDownloadScheme` and `makeIvarBedFile` processes altogether and directly supply the full path to an ivar-compatible bed file and a reference file.

I think that's either an independent issue and solution, or it supercedes this approach and we don't bother merging PR #12.

**Comment by sb10** [comment]
PR #12 merged
