### ISSUE TITLE
Provide own ivar bed file and aligner ref prefix

### ISSUE THREAD

**Issue by sb10** [wtsi-team112/ncov2019-artic-nf#14]
In a production environment, it is preferable to have a known fixed version of the bed file to be used with ivar, and to not waste a step of the workflow creating an ivar-compatible version every time.

Likewise, it is preferable to index the reference once and not repeat this every time the workflow is run.

**Comment by roamato** [comment]
I think this approach sounds better than justing providing a local copy of the repo as there is an LSF overhead in kicking off jobs. We could add an option with the location of the bed and, when present, the workflow steps those steps altogether?

Fasta could be an `if not present then index`, but we need to decide if that's also a command line option or a parameter in (one of) the config

**Comment by sb10** [comment]
Sorry, I implemented it before reading your comment, based on discussion with NPG.
Is the PR suitable for you as well?
