### ISSUE TITLE
Add CI testing

### ISSUE THREAD

**Issue by sb10** [wtsi-team112/ncov2019-artic-nf#20]
We need to be able to automate testing to ensure changes don't break the workflow.

**Comment by roamato** [comment]
Would be good to have CI/CD in place (I know it's easier in GitLab). @JonKeatley112 is the expert

**Comment by JonKeatley112** [comment]
I could do it on gitlab 🤣. Will look into doing it on gitinferior!

**Comment by sb10** [comment]
https://github.com/nf-core/rnaseq/blob/master/.travis.yml is an example travis file, but they don't seem to be testing the actual workflow outputs, which is something we'd need to do.

**Comment by JonKeatley112** [comment]
I think you can do it with `Actions` now https://github.com/wtsi-team112/ncov2019-artic-nf/actions/new

**Comment by JonKeatley112** [comment]
What testes would be need?

**Comment by sb10** [comment]
Test that workflow with hard-coded options produces expected output files.
Then a test for every new option we've created (cram, local scheme repo, changes in #17), and relevant combinations thereof, checking output files remain the same. (Or close enough, if there is a random seed at play)
Basic test that the workflow is syntactically correct, if that's possible.

**Comment by sb10** [comment]
If we use the upload features, ideally tests that the correct API calls are being made for the correct files, even though no upload actually happens.

**Comment by mgcam** [comment]
Test for files with no covid data - to ensure that the flow does not fail miserably

**Comment by sb10** [comment]
Tests have been in place for a while now. There isn't a "no covid data" test file, but there is a file that doesn't pass the QC, so hopefully that's good enough.
